apiVersion: v1
kind: Service
metadata:
  name: bbb-dev
spec:
  selector:
    app: bbb-dev
  ports:
  - port: 1900
    targetPort: core-port
    name: core-port
  - port: 6379
    targetPort: redis-port
    name: redis-port
